### ISSUE TITLE
working in 4.0.1 but without textures

### ISSUE THREAD

**Issue by arterror** [FScociety/Blender-Quixel-Bridge#1]
I installed your plug update in blender 4.0.1, but the textures are missing, any idea ???

**Comment by FScociety** [comment]
Hey, the official addon is currently only supported up to 3.6, so mine also is. They made some api changes for node groups. Maybe I can adapt it.

**Comment by arterror** [comment]
That would be awesome, TX

**Comment by FScociety** [comment]
hey, sorry for the late answer. It should now work in 4.0

**Comment by arterror** [comment]
Txxxxx, I will try now

**Comment by arterror** [comment]
working nice, extra thank you !!!!! on 4.0.2
